### PR TITLE
Parse (<function>+<addr>) backtrace format on POSIX systems

### LINKED ISSUE #356: test_stack_trace_decoding is failing on a fresh ubuntu18 install
Haven't had a chance to look at why.  Just adding this as a reminder.

### PR DESCRIPTION
**Pull request by justinboswell**
Fixes #356

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: source/posix/system_info.c [hunk 1]
```diff
@@ -191,7 +191,15 @@ int s_parse_symbol(const char *symbol, void *addr, struct aws_stack_frame_info *
...
     if (function_len > 0) { /* dynamic symbol was found */
-        strncpy(frame->function, open_paren + 1, function_len);
+        /* there might be (<function>+<addr>) or just (<function>) */
+        const char *function_start = open_paren + 1;
+        const char *plus = strstr(function_start, "+");
+        const char *function_end = (plus) ? plus : close_paren;
+        if (function_end > function_start) {
+            strncpy(frame->function, function_start, function_end - function_start);
+        } else if (plus) {
+            strncpy(frame->addr, plus + 1, close_paren - plus - 1);
```
Comment (bretambrose) [inline source/posix/system_info.c]: Doesn't this need a closing 0 byte?  You've already unconditionally copied the [] address into a buffer on line 190 and this is likely shorter

Comment (justinboswell) [reply source/posix/system_info.c]: Good catch.
